title: Islande Derazin # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>I am currently in my senior year at Brooklyn College, pursuing an undergraduate degree in Computer
Science. Last summer, I had the opportunity to work at Paul, Weiss, Rifkind, Wharton & Garrison LLP as
an IS Support Service Intern. My initial experiences were gathered by sitting in on phone calls and
reviewing incoming emails with Help Desk agents. I assisted on a knowledge-based project under my
assigned mentor’s guidance. We used MS Excel to review over 200 entries from Lotus Notes Online Help
to transfer to ServiceNow. While performing this evaluation, the analysts were able to find different
documentations easier. Which allowed the firm to run more efficiently.
Two semesters ago I decided to change my major from Biology to Computer Science with an interest in
Cybersecurity. As more people are sharing personal information over the internet, they are becoming
more exposed to cyber threats. As a long-term goal, I would like to be a part of a team that works to
keep people and organization safe online.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/islande-derazin/">View My LinkedIn Profile</a>
  <a href="https://www.linkedin.com/in/islande-derazin/">View My Resume</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
