title: Islande Derazin # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently in my senior year at Brooklyn College pursuing an undergraduate degree in Computer Science

  <br><br>
  Two semesters ago I decided to change my major from Biology to Computer Science with an interest in
Cybersecurity. As more people are sharing personal information over the internet, they are becoming
more exposed to cyber threats. As a long-term goal, I would like to be a part of a team that works to
keep people and organization safe online. 

  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
